## To run:  docker-compose -f docker-compose.yaml up

version: '3'

services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    volumes:
     - ./data:/var/www/data
     - ./mediawiki_LocalSettings.php:/var/www/html/LocalSettings.php
     