## To run:  docker-compose -f docker-compose.yaml up
##
## To stop:  CTRL+C
##      or:  docker-compose stop
##
## To remove:  docker-compose down
##

version: '3'

services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    volumes:
     - ./data:/var/www/data
     - ./mediawiki_LocalSettings.php:/var/www/html/LocalSettings.php
     